### ISSUE TITLE
error with [[inputs.execd]]

### ISSUE THREAD

**Issue by syswombat** [x70b1/telegraf-apt#2]
Hello
this part did not work for me.
First the command need a s at the end.
second i got error with the Signal Line
got error with the Interval command

and adding 
timeout = "10s"  - works to restart telegraf but after makes error because the scrtipt need to long.

[[inputs.execd]]
  command = ["/bin/sh", "/opt/telegraf/telegraf-apt.sh"]
  data_format = "influx"

  interval = "24h"
  signal = "SIGUSR1"

And why the script never stop just running it like this?

have a nice day
vinc

**Comment by x70b1** [comment]
This is a script that should never stop to run.
If you want to trigger it more often, change `interval`.

Compare [exec](https://github.com/influxdata/telegraf/tree/master/plugins/inputs/exec) and [execd](https://github.com/influxdata/telegraf/tree/master/plugins/inputs/execd).
