### ISSUE TITLE
I don't get all value in influxdb

### ISSUE THREAD

**Issue by judzk** [x70b1/telegraf-apt#4]
Hi, i got un debian bullseye with a influxdb2 and the last version of telegraf in docker
The script works, here my result 👍
```
sh telegraf-apt.sh
apt debian_release="11.5"
apt debian_codename="Bullseye"
apt debian_support=0
apt updates_regular=42
apt updates_security=29
apt updates_packages="base-files grep ncurses-bin libc6 libc-bin ncurses-base libsystemd0 systemd-timesyncd libnss-systemd libpam-systemd systemd udev libudev1 systemd-sysv libtasn1-6 libgnutls30 nftables libnftables1 debian-archive-keyring libk5crypto3 krb5-user libkrb5support0 libkrb5-3 libgssapi-krb5-2 libgssrpc4 libkadm5clnt-mit12 libkdb5-10 libkadm5srv-mit12 libssl1.1 libncurses6 libncursesw6 libtinfo6 tzdata isc-dhcp-client isc-dhcp-common nano libxml2 bind9-dnsutils bind9-libs bind9-host krb5-locales libc-l10n locales ncurses-term traceroute containerd.io curl libcurl4 distro-info-data docker-buildx-plugin docker-ce-cli docker-ce docker-ce-rootless-extras docker-compose-plugin docker-scan-plugin git-man libcurl3-gnutls git grub2-common grub-pc grub-pc-bin grub-common libksba8 libpq5 linux-image-5.10.0-23-amd64 linux-image-amd64 needrestart openssl postgresql-client-13 postgresql-13 sudo"
apt updates_severity=3
apt needrestart_services=2
apt needrestart_severity=1
```

But when i got in my influxn i got some value but not all :
codename, release, support are ok, but all the other are not.
Any idea?

**Comment by x70b1** [comment]
You could check the telegraf log output. Maybe you find something that points to the issue.

**Comment by judzk** [comment]
nothing in debug mode
2023-06-14T13:32:50Z D! [outputs.influxdb_v2] Wrote batch of 31 metrics in 48.254228ms
2023-06-14T13:32:50Z D! [outputs.influxdb_v2] Buffer fullness: 0 / 10000 metrics

**Comment by x70b1** [comment]
I dont use this plugin with InfluxDB v2. But it seems like the issue is not in this script.
You could check out telegrafs `-test` optinon and check which stats are collected.

**Comment by judzk** [comment]
Ok, now i got some error in my log
```
2023-06-14T14:12:19Z E! [inputs.execd] Error in plugin: read |0: file already closed
2023-06-14T14:12:19Z E! [inputs.execd] Error in plugin: error reading stderr: read |0: file already closed
2023-06-14T14:12:19Z I! [inputs.execd] Process /bin/sh shut down
2023-06-14T14:12:19Z D! [agent] Input channel closed

```

**Comment by x70b1** [comment]
Seems like somthing kills the script. You wrote you run it in docker. Can you give more details about the setup?

**Comment by judzk** [comment]
I think i figured it out.
- I must place inputs.execd first, if i put it after [[inputs.cpu]] or another another input, it doesn't work
- Don't work with docker
